[package]
name = "notifier-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
futures = "0.3.28"
rabbitmq-stream-client = "0.4.0"
tokio = { version = "1.33.0", features = ["full"] }

