[package]
name = "notifier-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
amqprs = "1.5.0"
anyhow = "1.0.75"
async-trait = "0.1.74"
dotenv = "0.15.0"
rabbitmq-stream-client = "0.4.0"
tokio = { version = "1.33.0", features = ["full"] }

