[package]
name = "controller"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
dotenv = "0.15.0"
futures-util = "0.3.28"
gilrs = "0.10.2"
tokio = { version = "1.33.0", features = ["full"] }
tokio-tungstenite = "0.20.1"
url = "2.4.1"
